-- Auto-generated from schema-map-postgres.psd1 (map@62c9c93)
-- engine: postgres
-- table:  pq_migration_jobs
CREATE TABLE IF NOT EXISTS pq_migration_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope TEXT NOT NULL,                         -- 'hashes' | 'wrappers' | 'signatures'
  target_policy_id BIGINT NULL,                -- encryption_policies.id (when switching the policy)
  target_algo_id BIGINT NULL,                  -- crypto_algorithms.id (e.g. ML-KEM-768)
  selection JSONB NULL,                        -- e.g. { "table": "encrypted_fields", "field": "ciphertext" }
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',      -- 'pending','running','done','failed','cancelled'
  processed_count BIGINT NOT NULL DEFAULT 0,
  error TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_pq_mig_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);
